### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by MasterDrake** [flecs-hub/flecs-lua#12]
Hi, I'm new to meson and ninja building but I was trying to see if these lua bindings work.
It fails at "ninja" step with this error:
![image](https://user-images.githubusercontent.com/51087997/186695763-00559a4c-c908-4125-85e8-79faeb95a20e.png)

Is this binding still being worked on or it's discontinued? I saw that the porting to 3.0.X is not done yet.

Thanks and sorry to bother you!

**Comment by randy408** [comment]
This is a flecs issue, are you using mingw?

**Comment by randy408** [comment]
Let's move this to https://github.com/SanderMertens/flecs/pull/983
